[log]
min_lvl=0
flush_on=0
filename=log/core.log
max_size=2
max_files=10

[sync]
write_queue_size=1024
thread_pool_size=20

[server]
addr=127.0.0.1:50051

[sqlite]
id=sqlite
path=./core.db
pool=1
msg_limit=1000

[issuer]
id=issuer
algo=0
pub_key=
pri_key=
encrypted_pub_key=
encrypted_pri_key=
valid_times=10000
leeway=30

[verifier]
id=verifier
algo=0
pub_key=
pri_key=
encrypted_pub_key=
encrypted_pri_key=

[asr]
ctxs = ggml-small-q8_0;
audio_buffer_size = 1600000
audio_min_chunk_size = 48000

[ggml-small-q8_0]
id = ggml/ggml-small-q8_0
path = ./models/ggml-small-q8_0.bin
use_gpu = 1
gpu_device = 0

[llm]
ctx_window_sz = 4096
num_threads = 1
max_repeats = 7
; models = 
; models = gemma-4-12B-it-Q8_0
models = SmolVLM2-256M-Video-Instruct-Q8_0

[SmolVLM2-256M-Video-Instruct-Q8_0]
id = bartowski/SmolVLM2-256M-Video-Instruct-Q8_0
path = ./models/SmolVLM2-256M-Video-Instruct-Q8_0.gguf
n_gpu_layers = -1
; split_mode:
;   0:single GPU
;   1:split layers and KV across GPUs
;   2:split layers and KV across GPUs, use tensor parallelism if supported
;   3:tensor
split_mode = 1
; main_gpu: the GPU that is used for the entire model when split_mode is single GPU
main_gpu = 0
; vocab_only: only load the vocabulary, no weights
vocab_only = 0
; use_mmap: use mmap if possible
use_mmap = 1
; use_direct_io: use direct io, takes precedence over use_mmap when supported
use_direct_io = 0
; use_mlock: force system to keep model in RAM
use_mlock = 0
; check_tensors: validate model tensor data
check_tensors = 0
; use_extra_bufts: use extra buffer types (used for weight repacking)
use_extra_bufts = 1
; no_host: bypass host buffer allowing extra buffers to be used
no_host = 0
; no_alloc: only load metadata and simulate memory allocations
no_alloc = 0

; [gemma-4-12B-it-Q8_0]
; id = google/gemma-4-12B-it-Q8_0
; path = ./models/gemma-4-12B-it-Q8_0.gguf
; n_gpu_layers = -1
; ; split_mode:
; ;   0:single GPU
; ;   1:split layers and KV across GPUs
; ;   2:split layers and KV across GPUs, use tensor parallelism if supported
; ;   3:tensor
; split_mode = 1
; ; main_gpu: the GPU that is used for the entire model when split_mode is single GPU
; main_gpu = 0
; ; vocab_only: only load the vocabulary, no weights
; vocab_only = 0
; ; use_mmap: use mmap if possible
; use_mmap = 1
; ; use_direct_io: use direct io, takes precedence over use_mmap when supported
; use_direct_io = 0
; ; use_mlock: force system to keep model in RAM
; use_mlock = 0
; ; check_tensors: validate model tensor data
; check_tensors = 0
; ; use_extra_bufts: use extra buffer types (used for weight repacking)
; use_extra_bufts = 1
; ; no_host: bypass host buffer allowing extra buffers to be used
; no_host = 0
; ; no_alloc: only load metadata and simulate memory allocations
; no_alloc = 0