// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api.proto

#include "api.pb.h"
#include "api.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace GrpcLibrary {

static const char* GrpcService_method_names[] = {
  "/GrpcLibrary.GrpcService/Login",
  "/GrpcLibrary.GrpcService/Logout",
  "/GrpcLibrary.GrpcService/RegAccount",
  "/GrpcLibrary.GrpcService/Query",
  "/GrpcLibrary.GrpcService/GetMessageInfo",
  "/GrpcLibrary.GrpcService/GetSession",
  "/GrpcLibrary.GrpcService/NewSession",
  "/GrpcLibrary.GrpcService/ModifySessionTitle",
  "/GrpcLibrary.GrpcService/DelSession",
  "/GrpcLibrary.GrpcService/GetSkillInfo",
  "/GrpcLibrary.GrpcService/Download",
};

std::unique_ptr< GrpcService::Stub> GrpcService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< GrpcService::Stub> stub(new GrpcService::Stub(channel, options));
  return stub;
}

GrpcService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Login_(GrpcService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Logout_(GrpcService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RegAccount_(GrpcService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Query_(GrpcService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_GetMessageInfo_(GrpcService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSession_(GrpcService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NewSession_(GrpcService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ModifySessionTitle_(GrpcService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DelSession_(GrpcService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetSkillInfo_(GrpcService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Download_(GrpcService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status GrpcService::Stub::Login(::grpc::ClientContext* context, const ::GrpcLibrary::LoginReq& request, ::GrpcLibrary::LoginResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GrpcLibrary::LoginReq, ::GrpcLibrary::LoginResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void GrpcService::Stub::async::Login(::grpc::ClientContext* context, const ::GrpcLibrary::LoginReq* request, ::GrpcLibrary::LoginResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GrpcLibrary::LoginReq, ::GrpcLibrary::LoginResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void GrpcService::Stub::async::Login(::grpc::ClientContext* context, const ::GrpcLibrary::LoginReq* request, ::GrpcLibrary::LoginResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::LoginResp>* GrpcService::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::GrpcLibrary::LoginReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GrpcLibrary::LoginResp, ::GrpcLibrary::LoginReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::LoginResp>* GrpcService::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::GrpcLibrary::LoginReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status GrpcService::Stub::Logout(::grpc::ClientContext* context, const ::GrpcLibrary::LogoutReq& request, ::GrpcLibrary::LogoutResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GrpcLibrary::LogoutReq, ::GrpcLibrary::LogoutResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Logout_, context, request, response);
}

void GrpcService::Stub::async::Logout(::grpc::ClientContext* context, const ::GrpcLibrary::LogoutReq* request, ::GrpcLibrary::LogoutResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GrpcLibrary::LogoutReq, ::GrpcLibrary::LogoutResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Logout_, context, request, response, std::move(f));
}

void GrpcService::Stub::async::Logout(::grpc::ClientContext* context, const ::GrpcLibrary::LogoutReq* request, ::GrpcLibrary::LogoutResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Logout_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::LogoutResp>* GrpcService::Stub::PrepareAsyncLogoutRaw(::grpc::ClientContext* context, const ::GrpcLibrary::LogoutReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GrpcLibrary::LogoutResp, ::GrpcLibrary::LogoutReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Logout_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::LogoutResp>* GrpcService::Stub::AsyncLogoutRaw(::grpc::ClientContext* context, const ::GrpcLibrary::LogoutReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLogoutRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status GrpcService::Stub::RegAccount(::grpc::ClientContext* context, const ::GrpcLibrary::RegAccountReq& request, ::GrpcLibrary::RegAccountResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GrpcLibrary::RegAccountReq, ::GrpcLibrary::RegAccountResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegAccount_, context, request, response);
}

void GrpcService::Stub::async::RegAccount(::grpc::ClientContext* context, const ::GrpcLibrary::RegAccountReq* request, ::GrpcLibrary::RegAccountResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GrpcLibrary::RegAccountReq, ::GrpcLibrary::RegAccountResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegAccount_, context, request, response, std::move(f));
}

void GrpcService::Stub::async::RegAccount(::grpc::ClientContext* context, const ::GrpcLibrary::RegAccountReq* request, ::GrpcLibrary::RegAccountResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegAccount_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::RegAccountResp>* GrpcService::Stub::PrepareAsyncRegAccountRaw(::grpc::ClientContext* context, const ::GrpcLibrary::RegAccountReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GrpcLibrary::RegAccountResp, ::GrpcLibrary::RegAccountReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegAccount_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::RegAccountResp>* GrpcService::Stub::AsyncRegAccountRaw(::grpc::ClientContext* context, const ::GrpcLibrary::RegAccountReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegAccountRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::GrpcLibrary::QueryResp>* GrpcService::Stub::QueryRaw(::grpc::ClientContext* context, const ::GrpcLibrary::QueryReq& request) {
  return ::grpc::internal::ClientReaderFactory< ::GrpcLibrary::QueryResp>::Create(channel_.get(), rpcmethod_Query_, context, request);
}

void GrpcService::Stub::async::Query(::grpc::ClientContext* context, const ::GrpcLibrary::QueryReq* request, ::grpc::ClientReadReactor< ::GrpcLibrary::QueryResp>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::GrpcLibrary::QueryResp>::Create(stub_->channel_.get(), stub_->rpcmethod_Query_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::GrpcLibrary::QueryResp>* GrpcService::Stub::AsyncQueryRaw(::grpc::ClientContext* context, const ::GrpcLibrary::QueryReq& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::GrpcLibrary::QueryResp>::Create(channel_.get(), cq, rpcmethod_Query_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::GrpcLibrary::QueryResp>* GrpcService::Stub::PrepareAsyncQueryRaw(::grpc::ClientContext* context, const ::GrpcLibrary::QueryReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::GrpcLibrary::QueryResp>::Create(channel_.get(), cq, rpcmethod_Query_, context, request, false, nullptr);
}

::grpc::Status GrpcService::Stub::GetMessageInfo(::grpc::ClientContext* context, const ::GrpcLibrary::GetMessageInfoReq& request, ::GrpcLibrary::GetMessageInfoResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GrpcLibrary::GetMessageInfoReq, ::GrpcLibrary::GetMessageInfoResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetMessageInfo_, context, request, response);
}

void GrpcService::Stub::async::GetMessageInfo(::grpc::ClientContext* context, const ::GrpcLibrary::GetMessageInfoReq* request, ::GrpcLibrary::GetMessageInfoResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GrpcLibrary::GetMessageInfoReq, ::GrpcLibrary::GetMessageInfoResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMessageInfo_, context, request, response, std::move(f));
}

void GrpcService::Stub::async::GetMessageInfo(::grpc::ClientContext* context, const ::GrpcLibrary::GetMessageInfoReq* request, ::GrpcLibrary::GetMessageInfoResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMessageInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::GetMessageInfoResp>* GrpcService::Stub::PrepareAsyncGetMessageInfoRaw(::grpc::ClientContext* context, const ::GrpcLibrary::GetMessageInfoReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GrpcLibrary::GetMessageInfoResp, ::GrpcLibrary::GetMessageInfoReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetMessageInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::GetMessageInfoResp>* GrpcService::Stub::AsyncGetMessageInfoRaw(::grpc::ClientContext* context, const ::GrpcLibrary::GetMessageInfoReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetMessageInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status GrpcService::Stub::GetSession(::grpc::ClientContext* context, const ::GrpcLibrary::GetSessionReq& request, ::GrpcLibrary::GetSessionResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GrpcLibrary::GetSessionReq, ::GrpcLibrary::GetSessionResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSession_, context, request, response);
}

void GrpcService::Stub::async::GetSession(::grpc::ClientContext* context, const ::GrpcLibrary::GetSessionReq* request, ::GrpcLibrary::GetSessionResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GrpcLibrary::GetSessionReq, ::GrpcLibrary::GetSessionResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSession_, context, request, response, std::move(f));
}

void GrpcService::Stub::async::GetSession(::grpc::ClientContext* context, const ::GrpcLibrary::GetSessionReq* request, ::GrpcLibrary::GetSessionResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSession_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::GetSessionResp>* GrpcService::Stub::PrepareAsyncGetSessionRaw(::grpc::ClientContext* context, const ::GrpcLibrary::GetSessionReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GrpcLibrary::GetSessionResp, ::GrpcLibrary::GetSessionReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSession_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::GetSessionResp>* GrpcService::Stub::AsyncGetSessionRaw(::grpc::ClientContext* context, const ::GrpcLibrary::GetSessionReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSessionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status GrpcService::Stub::NewSession(::grpc::ClientContext* context, const ::GrpcLibrary::NewSessionReq& request, ::GrpcLibrary::NewSessionResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GrpcLibrary::NewSessionReq, ::GrpcLibrary::NewSessionResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NewSession_, context, request, response);
}

void GrpcService::Stub::async::NewSession(::grpc::ClientContext* context, const ::GrpcLibrary::NewSessionReq* request, ::GrpcLibrary::NewSessionResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GrpcLibrary::NewSessionReq, ::GrpcLibrary::NewSessionResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NewSession_, context, request, response, std::move(f));
}

void GrpcService::Stub::async::NewSession(::grpc::ClientContext* context, const ::GrpcLibrary::NewSessionReq* request, ::GrpcLibrary::NewSessionResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NewSession_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::NewSessionResp>* GrpcService::Stub::PrepareAsyncNewSessionRaw(::grpc::ClientContext* context, const ::GrpcLibrary::NewSessionReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GrpcLibrary::NewSessionResp, ::GrpcLibrary::NewSessionReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NewSession_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::NewSessionResp>* GrpcService::Stub::AsyncNewSessionRaw(::grpc::ClientContext* context, const ::GrpcLibrary::NewSessionReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNewSessionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status GrpcService::Stub::ModifySessionTitle(::grpc::ClientContext* context, const ::GrpcLibrary::ModifySessionTitleReq& request, ::GrpcLibrary::ModifySessionTitleResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GrpcLibrary::ModifySessionTitleReq, ::GrpcLibrary::ModifySessionTitleResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ModifySessionTitle_, context, request, response);
}

void GrpcService::Stub::async::ModifySessionTitle(::grpc::ClientContext* context, const ::GrpcLibrary::ModifySessionTitleReq* request, ::GrpcLibrary::ModifySessionTitleResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GrpcLibrary::ModifySessionTitleReq, ::GrpcLibrary::ModifySessionTitleResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ModifySessionTitle_, context, request, response, std::move(f));
}

void GrpcService::Stub::async::ModifySessionTitle(::grpc::ClientContext* context, const ::GrpcLibrary::ModifySessionTitleReq* request, ::GrpcLibrary::ModifySessionTitleResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ModifySessionTitle_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::ModifySessionTitleResp>* GrpcService::Stub::PrepareAsyncModifySessionTitleRaw(::grpc::ClientContext* context, const ::GrpcLibrary::ModifySessionTitleReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GrpcLibrary::ModifySessionTitleResp, ::GrpcLibrary::ModifySessionTitleReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ModifySessionTitle_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::ModifySessionTitleResp>* GrpcService::Stub::AsyncModifySessionTitleRaw(::grpc::ClientContext* context, const ::GrpcLibrary::ModifySessionTitleReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncModifySessionTitleRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status GrpcService::Stub::DelSession(::grpc::ClientContext* context, const ::GrpcLibrary::DelSessionReq& request, ::GrpcLibrary::DelSessionResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GrpcLibrary::DelSessionReq, ::GrpcLibrary::DelSessionResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DelSession_, context, request, response);
}

void GrpcService::Stub::async::DelSession(::grpc::ClientContext* context, const ::GrpcLibrary::DelSessionReq* request, ::GrpcLibrary::DelSessionResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GrpcLibrary::DelSessionReq, ::GrpcLibrary::DelSessionResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DelSession_, context, request, response, std::move(f));
}

void GrpcService::Stub::async::DelSession(::grpc::ClientContext* context, const ::GrpcLibrary::DelSessionReq* request, ::GrpcLibrary::DelSessionResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DelSession_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::DelSessionResp>* GrpcService::Stub::PrepareAsyncDelSessionRaw(::grpc::ClientContext* context, const ::GrpcLibrary::DelSessionReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GrpcLibrary::DelSessionResp, ::GrpcLibrary::DelSessionReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DelSession_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::DelSessionResp>* GrpcService::Stub::AsyncDelSessionRaw(::grpc::ClientContext* context, const ::GrpcLibrary::DelSessionReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDelSessionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status GrpcService::Stub::GetSkillInfo(::grpc::ClientContext* context, const ::GrpcLibrary::GetSkillInfoReq& request, ::GrpcLibrary::GetSkillInfoResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GrpcLibrary::GetSkillInfoReq, ::GrpcLibrary::GetSkillInfoResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetSkillInfo_, context, request, response);
}

void GrpcService::Stub::async::GetSkillInfo(::grpc::ClientContext* context, const ::GrpcLibrary::GetSkillInfoReq* request, ::GrpcLibrary::GetSkillInfoResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GrpcLibrary::GetSkillInfoReq, ::GrpcLibrary::GetSkillInfoResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSkillInfo_, context, request, response, std::move(f));
}

void GrpcService::Stub::async::GetSkillInfo(::grpc::ClientContext* context, const ::GrpcLibrary::GetSkillInfoReq* request, ::GrpcLibrary::GetSkillInfoResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetSkillInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::GetSkillInfoResp>* GrpcService::Stub::PrepareAsyncGetSkillInfoRaw(::grpc::ClientContext* context, const ::GrpcLibrary::GetSkillInfoReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GrpcLibrary::GetSkillInfoResp, ::GrpcLibrary::GetSkillInfoReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetSkillInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::GetSkillInfoResp>* GrpcService::Stub::AsyncGetSkillInfoRaw(::grpc::ClientContext* context, const ::GrpcLibrary::GetSkillInfoReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetSkillInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status GrpcService::Stub::Download(::grpc::ClientContext* context, const ::GrpcLibrary::DownloadReq& request, ::GrpcLibrary::DownloadResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GrpcLibrary::DownloadReq, ::GrpcLibrary::DownloadResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Download_, context, request, response);
}

void GrpcService::Stub::async::Download(::grpc::ClientContext* context, const ::GrpcLibrary::DownloadReq* request, ::GrpcLibrary::DownloadResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GrpcLibrary::DownloadReq, ::GrpcLibrary::DownloadResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Download_, context, request, response, std::move(f));
}

void GrpcService::Stub::async::Download(::grpc::ClientContext* context, const ::GrpcLibrary::DownloadReq* request, ::GrpcLibrary::DownloadResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Download_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::DownloadResp>* GrpcService::Stub::PrepareAsyncDownloadRaw(::grpc::ClientContext* context, const ::GrpcLibrary::DownloadReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GrpcLibrary::DownloadResp, ::GrpcLibrary::DownloadReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Download_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GrpcLibrary::DownloadResp>* GrpcService::Stub::AsyncDownloadRaw(::grpc::ClientContext* context, const ::GrpcLibrary::DownloadReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDownloadRaw(context, request, cq);
  result->StartCall();
  return result;
}

GrpcService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GrpcService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GrpcService::Service, ::GrpcLibrary::LoginReq, ::GrpcLibrary::LoginResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GrpcService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GrpcLibrary::LoginReq* req,
             ::GrpcLibrary::LoginResp* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GrpcService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GrpcService::Service, ::GrpcLibrary::LogoutReq, ::GrpcLibrary::LogoutResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GrpcService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GrpcLibrary::LogoutReq* req,
             ::GrpcLibrary::LogoutResp* resp) {
               return service->Logout(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GrpcService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GrpcService::Service, ::GrpcLibrary::RegAccountReq, ::GrpcLibrary::RegAccountResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GrpcService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GrpcLibrary::RegAccountReq* req,
             ::GrpcLibrary::RegAccountResp* resp) {
               return service->RegAccount(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GrpcService_method_names[3],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< GrpcService::Service, ::GrpcLibrary::QueryReq, ::GrpcLibrary::QueryResp>(
          [](GrpcService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GrpcLibrary::QueryReq* req,
             ::grpc::ServerWriter<::GrpcLibrary::QueryResp>* writer) {
               return service->Query(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GrpcService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GrpcService::Service, ::GrpcLibrary::GetMessageInfoReq, ::GrpcLibrary::GetMessageInfoResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GrpcService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GrpcLibrary::GetMessageInfoReq* req,
             ::GrpcLibrary::GetMessageInfoResp* resp) {
               return service->GetMessageInfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GrpcService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GrpcService::Service, ::GrpcLibrary::GetSessionReq, ::GrpcLibrary::GetSessionResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GrpcService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GrpcLibrary::GetSessionReq* req,
             ::GrpcLibrary::GetSessionResp* resp) {
               return service->GetSession(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GrpcService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GrpcService::Service, ::GrpcLibrary::NewSessionReq, ::GrpcLibrary::NewSessionResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GrpcService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GrpcLibrary::NewSessionReq* req,
             ::GrpcLibrary::NewSessionResp* resp) {
               return service->NewSession(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GrpcService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GrpcService::Service, ::GrpcLibrary::ModifySessionTitleReq, ::GrpcLibrary::ModifySessionTitleResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GrpcService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GrpcLibrary::ModifySessionTitleReq* req,
             ::GrpcLibrary::ModifySessionTitleResp* resp) {
               return service->ModifySessionTitle(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GrpcService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GrpcService::Service, ::GrpcLibrary::DelSessionReq, ::GrpcLibrary::DelSessionResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GrpcService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GrpcLibrary::DelSessionReq* req,
             ::GrpcLibrary::DelSessionResp* resp) {
               return service->DelSession(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GrpcService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GrpcService::Service, ::GrpcLibrary::GetSkillInfoReq, ::GrpcLibrary::GetSkillInfoResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GrpcService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GrpcLibrary::GetSkillInfoReq* req,
             ::GrpcLibrary::GetSkillInfoResp* resp) {
               return service->GetSkillInfo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      GrpcService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< GrpcService::Service, ::GrpcLibrary::DownloadReq, ::GrpcLibrary::DownloadResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](GrpcService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GrpcLibrary::DownloadReq* req,
             ::GrpcLibrary::DownloadResp* resp) {
               return service->Download(ctx, req, resp);
             }, this)));
}

GrpcService::Service::~Service() {
}

::grpc::Status GrpcService::Service::Login(::grpc::ServerContext* context, const ::GrpcLibrary::LoginReq* request, ::GrpcLibrary::LoginResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GrpcService::Service::Logout(::grpc::ServerContext* context, const ::GrpcLibrary::LogoutReq* request, ::GrpcLibrary::LogoutResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GrpcService::Service::RegAccount(::grpc::ServerContext* context, const ::GrpcLibrary::RegAccountReq* request, ::GrpcLibrary::RegAccountResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GrpcService::Service::Query(::grpc::ServerContext* context, const ::GrpcLibrary::QueryReq* request, ::grpc::ServerWriter< ::GrpcLibrary::QueryResp>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GrpcService::Service::GetMessageInfo(::grpc::ServerContext* context, const ::GrpcLibrary::GetMessageInfoReq* request, ::GrpcLibrary::GetMessageInfoResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GrpcService::Service::GetSession(::grpc::ServerContext* context, const ::GrpcLibrary::GetSessionReq* request, ::GrpcLibrary::GetSessionResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GrpcService::Service::NewSession(::grpc::ServerContext* context, const ::GrpcLibrary::NewSessionReq* request, ::GrpcLibrary::NewSessionResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GrpcService::Service::ModifySessionTitle(::grpc::ServerContext* context, const ::GrpcLibrary::ModifySessionTitleReq* request, ::GrpcLibrary::ModifySessionTitleResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GrpcService::Service::DelSession(::grpc::ServerContext* context, const ::GrpcLibrary::DelSessionReq* request, ::GrpcLibrary::DelSessionResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GrpcService::Service::GetSkillInfo(::grpc::ServerContext* context, const ::GrpcLibrary::GetSkillInfoReq* request, ::GrpcLibrary::GetSkillInfoResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status GrpcService::Service::Download(::grpc::ServerContext* context, const ::GrpcLibrary::DownloadReq* request, ::GrpcLibrary::DownloadResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace GrpcLibrary
#include <grpcpp/ports_undef.inc>

