function(load_env target)
	if(EXISTS "${target}")
		file(READ "${target}" ENV_CONTENTS)
		string(REPLACE "\n" ";" ENV_LINES "${ENV_CONTENTS}")
		foreach(line ${ENV_LINES})
			string(REGEX MATCH "^([A-Za-z0-9_]+)=(.*)$" _match "${line}")
			if(_match)
				set(var_name "${CMAKE_MATCH_1}")
				set(var_value "${CMAKE_MATCH_2}")
				set(${var_name} "${var_value}" PARENT_SCOPE)
			endif()
		endforeach()
	endif()
endfunction()