function(detect_triplet_platform OUT_VAR)
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(_ARCH "x64")
    elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
        set(_ARCH "x86")
    else()
        set(_ARCH "unknown")
    endif()

    if(WIN32)
        set(_PLATFORM "windows")
    elseif(APPLE)
        set(_PLATFORM "osx")
    elseif(UNIX)
        set(_PLATFORM "linux")
    else()
        set(_PLATFORM "unknown")
    endif()

    set(_TRIPLET "${_ARCH}-${_PLATFORM}")
    set(${OUT_VAR} "${_TRIPLET}" PARENT_SCOPE)
endfunction()